#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "2fauth"
name = "2FAuth"
description.en = "Generate and organize your two-factor authentication codes"
description.fr = "Générez et organisez vos codes d'authentification à deux facteurs"

version = "7.0.1~ynh3"

maintainers = []

[upstream]
license = "AGPL-3.0"
demo = "https://demo.2fauth.app/login"
admindoc = "https://docs.2fauth.app/"
code = "https://github.com/Bubka/2FAuth"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Bubka/2FAuth/archive/refs/tags/v7.0.1.tar.gz"
    sha256 = "6f700ae52a6ad73ab9aee57baf07c2981c80f60190b7b997316a44a5cc7697bf"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"
    api.auth_header = false

    [resources.apt]
    packages = "mariadb-server, redis-server, php8.5-bcmath, php8.5-xml, php8.5-mbstring, php8.5-gd, php8.5-mysql, php8.5-curl"

    [resources.database]
    type = "mysql"

    [resources.composer]
    version = "2.10.1"
