#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {
    root __INSTALL_DIR__/public/;

    client_max_body_size 50m;
    
    index index.php;
    
    try_files $uri $uri/ @__APP___subpath;

    location = __PATH__/favicon.ico {
        alias __INSTALL_DIR__/public/favicon.ico;
        access_log off;
        log_not_found off;
        expires 30d;
    }

    location = __PATH__/robots.txt {
        alias __INSTALL_DIR__/public/robots.txt;
        access_log off;
        log_not_found off;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~ \.php$ {
        if (!-f $request_filename) {
            return 404;
        }

        fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
        include fastcgi_params_with_auth;
    }
}

# Fallback for clean URLs
location @__APP___subpath {
    rewrite __PATH__/(.*)$ __PATH__/index.php?/$1 last;
}
