#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  root __INSTALL_DIR__/public/;

  client_max_body_size 50m;

  index index.php;

  location = __PATH__/favicon.ico { access_log off; log_not_found off; }
  location = __PATH__/robots.txt  { access_log off; log_not_found off; }

  location ~ /\.(?!well-known).* {
          deny all;
  }

  error_page 404 __PATH__/index.php;

  try_files $uri $uri/ __PATH__/__PATH__/index.php?$query_string;
  
  location ~ [^/]\.php(/|$) {
   if (!-e $request_filename) {
      rewrite ^__PATH__/?(.*)$ __PATH__/index.php?/$1 last;
      break;
    }
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    include fastcgi_params_with_auth;
  }
}
