#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

ynh_backup_if_checksum_is_different "$install_dir/.env"
ynh_delete_file_checksum "$install_dir/.env"

ynh_replace --match="'${old_domain}'" --replace="'${new_domain}'" --file="$install_dir/.env"

ynh_store_file_checksum "$install_dir/.env"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
