#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

# key for the .env __KEY__
key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=key --value=$key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# INSTALL 2FAUTH WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

ynh_composer_install
ynh_composer_exec install --no-dev  --prefer-dist --no-scripts --no-dev

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 640 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building $app..."

pushd $install_dir
	php$php_version artisan migrate:refresh -n
	php$php_version artisan passport:install -n
	php$php_version artisan storage:link -n
	php$php_version artisan config:cache -n
popd

chmod 775 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
