#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)

# key for the .env __KEY__
#key=$(ynh_string_random --length=32 | base64)
#ynh_app_setting_set --key=key --value=$key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 640 "$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# INSTALL 2FAUTH WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

ynh_composer_install
ynh_composer_exec install --prefer-dist --no-scripts --no-dev

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building $app..."

pushd $install_dir
	php$php_version artisan migrate:refresh -n
	php$php_version artisan key:generate
	php$php_version artisan passport:install -n
	php$php_version artisan storage:link -n
	php$php_version artisan config:cache -n
popd

ynh_delete_file_checksum "$install_dir/.env"
ynh_store_file_checksum "$install_dir/.env"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
