#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)
fpm_footprint="low"
fpm_free_footprint=0
fpm_usage="low"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --app=$app --key=fpm_footprint --value=$fpm_footprint
ynh_app_setting_set --app=$app --key=fpm_free_footprint --value=$fpm_free_footprint
ynh_app_setting_set --app=$app --key=fpm_usage --value=$fpm_usage

# key for the .env __KEY__
key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --app=$app --key=key --value=$key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..." --weight=2

ynh_add_fpm_config --usage=$fpm_usage --footprint=$fpm_footprint

ynh_add_nginx_config

#=================================================
# INSTALL 2FAUTH WITH COMPOSER
#=================================================
ynh_script_progression --message="Installing $app with Composer..." --weight=15

ynh_install_composer --install_args="--prefer-dist --no-scripts --no-dev"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

# Setup application config
ynh_add_config --template=".env.example" --destination="$install_dir/.env"

chmod 644 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# BUILDING
#=================================================
ynh_script_progression --message="Building $app..." --weight=10

# Setup application config
pushd $install_dir
	php$phpversion artisan migrate:refresh -n
	php$phpversion artisan passport:install -n
	php$phpversion artisan storage:link -n
	php$phpversion artisan config:cache -n
popd

chmod 775 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
