#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# FIXME: maybe replace with: ynh_app_setting_set_default --key=key --value=$(ynh_string_random --length=45 | base64)
if [ -z "${key:-}" ]; then
	key=$(ynh_string_random --length=45 | base64)
	ynh_app_setting_set --key=key --value=$key
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="public/storage storage .env"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading PHP-FPM configuration..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Upgrading a configuration file..."

# Setup application config
ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 640 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# INSTALL 2FAUTH WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

ynh_safe_rm $install_dir/package-lock.json

ynh_composer_install
ynh_composer_exec install --no-dev  --ignore-platform-reqs --prefer-dist --no-scripts --no-dev

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building..."

ynh_composer_exec update

# Setup application config
pushd $install_dir
	php$php_version artisan cache:clear
	php$php_version artisan config:clear
	php$php_version artisan migrate -n
	php$php_version artisan passport:install -n
	php$php_version artisan config:cache -n
	php$php_version artisan route:cache
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
