#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# If fpm_footprint doesn't exist, create it
if [ -z "${fpm_footprint:-}" ]; then
    fpm_footprint=low
    ynh_app_setting_set --app=$app --key=fpm_footprint --value=$fpm_footprint
fi

# If fpm_free_footprint doesn't exist, create it
if [ -z "${fpm_free_footprint:-}" ]; then
    fpm_free_footprint=0
    ynh_app_setting_set --app=$app --key=fpm_free_footprint --value=$fpm_free_footprint
fi

# If fpm_usage doesn't exist, create it
if [ -z "${fpm_usage:-}" ]; then
    fpm_usage=low
    ynh_app_setting_set --app=$app --key=fpm_usage --value=$fpm_usage
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=3

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --keep="storage .env"
fi

chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --phpversion=$phpversion --usage=$fpm_usage --footprint=$fpm_footprint

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# ADD A CONFIGURATION
#=================================================
#ynh_script_progression --message="Adding a configuration file..." --weight=1

#email=$(ynh_user_get_info --username=$admin --key=mail)

# Setup application config
#ynh_add_config --template="../conf/.env.example" --destination="$install_dir/.env"

#chmod 644 "$install_dir/.env"
#chown $app:$app "$install_dir/.env"

#=================================================
# INSTALL 2FAUTH WITH COMPOSER
#=================================================
ynh_script_progression --message="Installing $app with Composer..." --weight=15

ynh_secure_remove --file=$install_dir/package-lock.json

ynh_install_composer --install_args="--ignore-platform-reqs --prefer-dist --no-scripts --no-dev"

#=================================================
# BUILDING
#=================================================
ynh_script_progression --message="Building..." --weight=10

ynh_exec_warn_less ynh_composer_exec --commands="update"

# Setup application config
pushd $install_dir
	php$phpversion artisan cache:clear
	php$phpversion artisan config:clear
	php$phpversion artisan migrate -n
	php$phpversion artisan passport:install -n
	php$phpversion artisan config:cache -n
	php$phpversion artisan route:cache
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
