#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="public/storage storage .env"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating $app's configuration files..."

#ynh_config_add --template=".env" --destination="$install_dir/.env"

#chmod 640 "$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# INSTALL 2FAUTH WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

ynh_safe_rm $install_dir/package-lock.json

#REMOVEME? ynh_composer_install
ynh_composer_exec install --prefer-dist --no-scripts --no-dev

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building..."

ynh_composer_exec update

pushd $install_dir
	php$php_version artisan cache:clear
	php$php_version artisan config:clear
	php$php_version artisan migrate -n
	#php$php_version artisan key:generate
	php$php_version artisan passport:install -n
	php$php_version artisan config:cache -n
	php$php_version artisan route:cache
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
